server:
  port: 9090
  
spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-b661b63f-4fcf-4b9d-9274-8b49018cb596.cfapps.io
    register-with-eureka: false
    
zuul:
  routes:
    SkelopsProducer:
      path: /trex/addTRex
      url: https://skelopsproducer.cfapps.io
    
    SkelopsDemo:
      path: /trex/all
      url: https://skelopsdemo.cfapps.io

    